# =========================
# EXPERIMENT SETTING
# =========================
exp:
  feature_mode: 'baseline_full'  # dx, dy, dvx, dvy, dax, day
  device: 'cuda:0'
  seed: 42

# =========================
# DATA PATHS & PARAMS
# =========================
data:
  base_dir: 'highD'
  batch_size: 512
  num_workers: 32
  history_frames: 9   # 3 sec * 3 Hz
  future_frames: 15   # 5 sec * 3 Hz
  persistent_workers: True

# =========================
# MODEL PARAMS (GRIP++)
# =========================
model:
  max_hop: 2
  num_node: 9  # Ego + 8 Neighbors (MAX_NEIGHBORS + 1)
  edge_importance_weighting: true

# =========================
# TRAINING PARAMS
# =========================
train:
  epochs: 500
  lr: 0.0001
  weight_decay: 0.0001
  ckpt_dir: 'ckpts'
